### ISSUE TITLE
Missing CFLAGS and LDFLAGS in the build

### ISSUE THREAD

**Issue by kartikm** [spbooth/xmountains#10]
Can be tested by using bhlc tool.

Full log: https://salsa.debian.org/debian/xmountains/-/jobs/1381667

**Comment by spbooth** [comment]
The way this is supposed to work is that you run xmkmf (from the xutils-dev package on debian) to generate a system specific Makefile from the Imakefile
CFLAGS and LDFLAGS are not specified by the Imakefile but added from the local xmkmf config.
If additional flags are required/desirable for a debian build then surely they should be added by xmkmf

**Comment by kartikm** [comment]
Closing this. Fix applied to Debian.
