### ISSUE TITLE
ftbfs with GCC-10

### ISSUE THREAD

**Issue by kartikm** [spbooth/xmountains#7]
The package fails to build in a test rebuild on at least amd64 with gcc-10/g++-10, but succeeds to build with gcc-9/g++-9.

Log: http://people.debian.org/~doko/logs/gcc10-20200225/xmountains_2.9-6_unstable_gcc10.log

See issue at Debian BTS: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=957988

**Comment by reinerh** [comment]
Fixed in 070c9e3.
