### ISSUE TITLE
Download URL is no longer working

### ISSUE THREAD

**Issue by kartikm** [spbooth/xmountains#8]
xmountains download URL, http://www2.epcc.ed.ac.uk/~spb/xmountains/ seems not working (page not loading).

Please enable tags/releases from github and it should be better to track release, changelogs and tags.

Thanks!

**Comment by kartikm** [comment]
@spbooth Can you look at this?

**Comment by spbooth** [comment]
That download page has long since been retired. References to this URL should be removed
The support pages have been migrated to github pages https://spbooth.github.io/xmountains/

**Comment by spbooth** [comment]
Ive created a release from the 2.10 tag.
Though the amount of changes in this project have been very minimal
